### ISSUE TITLE
Debug tested application code

### ISSUE THREAD

**Issue by gejgalis** [tbosch/jasmine-ui#10]
Sometimes it is needed to set breakpoint in application code when tests are executed. Your implementation is reloading every time current window from tests runner to application URL and it is very hard to set breakpoint inside the browser. Did you consider running application inside IFRAME instead of reloading window? It would be easier to debug application which is loaded into the IFRAME. Of course this feature would be available for instance by additional parameter in URL : UiTestsRunner.html?debugIframe=true

Or maybe you have another solution for debugging tested code?

**Comment by tbosch** [comment]
Hi,
I usually first set a breakpoint in the beginning of the spec that I want to debug. When that breakpoint is reached, the application is loaded and you can set further breapoints in the application code. 
The refreshing should be no problem here, at least in Chrome. 

Using an iframe was omitted by purpose, as for mobile sites the layout gets destroyed...

A better solution to this problem would be to show the test results in the context of the last page of the application, i.e. when all application scripts are still loaded. I leave this ticket open for implementing this.

**Comment by gejgalis** [comment]
Nice hint! It should be enough to resolve my debug problem :)

Thank you,
Piotr
