### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by jperl** [tbosch/jasmine-ui#18]
This is in the latest from separate-loader-testfwk.

works:

``` html
<script type="text/javascript">eval(sessionStorage.jasmineui);</script>
```

causes an infinite loop:

``` html
<script type="text/javascript">
    eval(sessionStorage.jasmineui);
</script>
```

I will look further into it. I believe the matching function for the eval statement is limited: `var SCRIPT_RE = /<script([^>]*src=\s*"([^"]+))?[^>]*>(.*?)<\/script>/;`

**Comment by jperl** [comment]
I tried to fix this, but I am really bad with regex :(

**Comment by tbosch** [comment]
Hi,
thanks for trying the new branch! Yes, you are right, the regex is wrong. Problem is the `.*` here: This does not match newlines. In JavaScript, you need to use a hack like `[\s\S]*`. 

Tobias

**Comment by jperl** [comment]
Thank you for figuring it out!

**Comment by tbosch** [comment]
This has been fixed already by a previous commit...

Thanks!
Tobias
