### ISSUE TITLE
Window not opening when running test a second time

### ISSUE THREAD

**Issue by jroets** [tbosch/jasmine-ui#20]
Using jstestdriver, if I run my tests more than once in a row, subsequent runs result in the following error:

TypeError: Cannot read property 'tmp' of null

I traced this back to the fact that on subsequent runs, the new window is not being opened; and this is because you have a reference in "setPopupMode()" to a var "remoteWindow" which you are not resetting, so that when "itHander" is called, it thinks the window is still open from the first run. To workaround the problem, I added "remoteWindow = null" after calling "remoteWindow.close()" in "finishCallback".

**Comment by tbosch** [comment]
Hi,
thanks for reporting. I will check this!

Tobias

**Comment by tbosch** [comment]
Hi,
sorry for the delay. However, I have been working on the successor of jasmine-ui which is both simpler and more powerful with an easy migration path. I'll release it in the next two weeks or so. Stay tuned :-)

Tobias

**Comment by jroets** [comment]
I look forward to seeing what you have.

**Comment by tbosch** [comment]
My new project uitest.js does no more have this problem, and works great with testacular.

Jasmine-Ui has been superseded by uitest.js:
- Github: [https://github.com/tigbro/uitest.js](https://github.com/tigbro/uitest.js)
- Migration-Guide and why: [https://github.com/tigbro/uitest.js/blob/master/docs/jasmineUiMigration.md](https://github.com/tigbro/uitest.js/blob/master/docs/jasmineUiMigration.md).

Closing this as this project is no more active...
