### ISSUE TITLE
waitsForAsyncTimeout is not configurable

### ISSUE THREAD

**Issue by smithgp** [tbosch/jasmine-ui#24]
As far as I can tell, you can't configure `waitsForAsyncTimeout` to control the timeout on the initial page load in a `describeUi()`. I've got a webapp which does more than 5 seconds of XHRs onload. I'm running jasmine-ui 1.0.1 in testacular 0.4.0, which seems to work ok so far for some really simple tests.

In my environment, in the define for `config`, I've got a local fix/workaround that looks for a `persistentData().waitsForAsyncTimeout` (or defaults back to 5000), and then I have one of my js files set that a `require()`. Seems to work so far.

If that sounds ok, I can fork, test, and make a pull request.

**Comment by smithgp** [comment]
Looking in the separate-loader-testfwk branch, it looks like this might be fixed already. There's some code in `src/parts/config.js` which merges a `persistentData.config` into the return from the `define('config')`. I'll try that out.

**Comment by tbosch** [comment]
Hi, 
have a look at this: https://github.com/tigbro/jasmine-ui/tree/separate-loader-testfwk#configuration

Just set `jasmineuiConfig = {  waitsForAsyncTimeout: 10000 }

Tobias

**Comment by smithgp** [comment]
Hi. Sorry for the delay in getting back.

Yes, that does look like it would do the trick. I can't test it out right now because 1) our app no longer takes more than 5 seconds unload, and 2) the new branch got rid of the `describeUi()` and, more importantly, `jasmineui.inject()`, which our tests are relying on.

I'll reopen this it's still an issue when we upgrade to 1.1.0.

**Comment by tbosch** [comment]
Hi,
just a short note: I have been working on the successor of jasmine-ui which is both simpler and more powerful with an easy migration path. I'll release it in the next two weeks or so. Stay tuned :-)

Tobias
