### ISSUE TITLE
Make it possible to disable the setInterval sensor

### ISSUE THREAD

**Issue by rix0rrr** [tbosch/jasmine-ui#25]
I use some libraries (Sammy.js and TreeGrid.com) that use endless intervals internally, so Jasmine UI never stops waiting and the tests fail.

**Comment by tbosch** [comment]
Hi,
this is already possible using the branch https://github.com/tigbro/jasmine-ui/tree/separate-loader-testfwk, see here for the configuration: https://github.com/tigbro/jasmine-ui/tree/separate-loader-testfwk#configuration

Just set `jasmineuiConfig = {  asyncSensors: ['load', 'timeout', 'xhr', '$animationComplete', '$transitionComplete'] }` and everything should be fine. By default, this also includes the sensor `interval`.

Tobias

**Comment by tbosch** [comment]
Hi,
sorry for the delay. However, I have been working on the successor of jasmine-ui which is both simpler and more powerful with an easy migration path. I'll release it in the next two weeks or so. Stay tuned :-)

Tobias

**Comment by heiko-hardt** [comment]
sounds great :)

**Comment by tbosch** [comment]
In uitest.js you specify the wait sensors one by one via a call to the `feature` function (they are called `readySensors` there). 

Jasmine-Ui has been superseded by uitest.js:
- Github: [https://github.com/tigbro/uitest.js](https://github.com/tigbro/uitest.js)
- Migration-Guide and why: [https://github.com/tigbro/uitest.js/blob/master/docs/jasmineUiMigration.md](https://github.com/tigbro/uitest.js/blob/master/docs/jasmineUiMigration.md).

Closing this as this project is no more active...
