### ISSUE TITLE
Add a cache-busting parameter for the included scripts

### ISSUE THREAD

**Issue by rix0rrr** [tbosch/jasmine-ui#26]
Otherwise the tests sometimes fail when the browser decides to retrieve a source file from the cache.

Something long these lines in persistentData/serialize():

```
            var scripts = currentSpec.loadScripts;
            if (scripts) {
                var cacheBuster = '?t=' + new Date().getTime();
                for (var i = 0; i < scripts.length; i++) {
                    window.document.writeln('<script type="text/javascript" src="' + scripts[i] + cacheBuster + '"></script>');
                }
            }
```

**Comment by tbosch** [comment]
Good idea. Have to think about it...

**Comment by tbosch** [comment]
In uitest.js I already added cache busting.

Jasmine-Ui has been superseded by uitest.js:
- Github: [https://github.com/tigbro/uitest.js](https://github.com/tigbro/uitest.js)
- Migration-Guide and why: [https://github.com/tigbro/uitest.js/blob/master/docs/jasmineUiMigration.md](https://github.com/tigbro/uitest.js/blob/master/docs/jasmineUiMigration.md).

Closing this as this project is no more active...
