### ISSUE TITLE
Skipped tests aren't shown in spec runner result page.

### ISSUE THREAD

**Issue by stefanscheidt** [tbosch/jasmine-ui#4]
Make sure that skipped tests are shown in the spec runner result page when the option "show skipped" is selected.

**Comment by tbosch** [comment]
Jasmine only marks tests as skipped if they were filtered using a specFilter. E.g. with the default html runner, this would be the case when a single test is selected to execute alone.

**Comment by tbosch** [comment]
This is working now with the fix of #6.
