### ISSUE TITLE
Jasmine spec filter is not used by jasmine-ui

### ISSUE THREAD

**Issue by nwoike** [tbosch/jasmine-ui#6]
In the inplace mode, the Jasmine Spec Filter does not appear to used.

Need to add something like the following when you override the jasmineApi.jasmine.Runner.prototype.execute method.

```
if (!spec.env.specFilter(spec)) {
    spec.results_.skipped = true;
    continue;
}
```

**Comment by tbosch** [comment]
Hi,
yes, you are right. Thanks for trying this project!
By the way, how are you using the Spec Filters of Jasmine?

Tobias

**Comment by nwoike** [comment]
While test driving our code it is nice to only run single specs or a set of specs related to the story we are working on. 

Our spec runner contains the following:

```
var env = jasmine.getEnv(),
    trivialReporter = new jasmine.TrivialReporter();

 env.updateInterval = 3000;                     
 env.addReporter(trivialReporter);

 env.specFilter = function(spec) {
    return trivialReporter.specFilter(spec);
 };

 env.execute();
```

**Comment by tbosch** [comment]
Hi, sorry about the delay. I will include this soon!

**Comment by nwoike** [comment]
No rush I have switched over to using WebdriverJS with Jasmine. As much as I like your solution I wanted to move to something more standardized now in hopes that the w3c webdriver spec and ghost driver is finished.
